apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graphite-proxy
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: graphite-proxy
        task: monitoring
        output: grafana
    spec:
      containers:
        - name: carbon-replay-ng
          image: quay.io/adfin/k8-carbon-replay-ng
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          command: 
            - /bin/goenvtemplator
            - -template
            - /conf/carbon-relay-ng.ini.tmpl:/conf/carbon-relay-ng.ini
            - -exec
            - /bin/carbon-relay-ng
            - /conf/carbon-relay-ng.ini
          env:
            - name: "GRAFANA_METRIC_URL"
              valueFrom:
                secretKeyRef:
                  name: grafana
                  key: metric-url
            - name: "GRAFANA_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: grafana
                  key: api-key
          ports:
            - containerPort: 2003
            - containerPort: 2013
            - containerPort: 2004
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: graphite-proxy
  namespace: default
spec:
  selector:
    name: graphite-proxy
  ports:
    - name: graphite
      protocol: TCP
      port: 2003
      targetPort: 2003
    - name: graphite-pickle
      protocol: TCP
      port: 2013
      targetPort: 2013
    - name: graphite-admin
      protocol: TCP
      port: 2004
      targetPort: 2004
    - name: http-admin
      protocol: TCP
      port: 8081
      targetPort: 8081
